-- AlterTable
ALTER TABLE "products" ALTER COLUMN "height_cm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "length_cm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "width_cm" SET DATA TYPE DOUBLE PRECISION;
